document.write('<header>');
	document.write('<nav class="navbar navbar-toggleable-md navbar-light" style="background-color: #e3f2fd;">');
		document.write('<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">');
			document.write('<span class="navbar-toggler-icon"></span>');
	document.write('</button>');
	document.write('<a class="navbar-brand" href="#">Cady Gorbet</a>');
		document.write('<div class="collapse navbar-collapse" id="navbarSupportedContent">');
			document.write('<ul class="navbar-nav mr-auto">');
				document.write('<li class="nav-item active">');
					document.write('<a class="nav-link" href="#home">Home <span class="sr-only">(current)</span></a>');
				document.write('</li>');
				document.write('<li class="nav-item">');
					document.write('<a class="nav-link" href="#about.html">About</a>');
				document.write('</li>');
			document.write('</ul>');
		document.write('</div>');
	document.write('</nav>');
document.write('</header>');